# -*- coding: utf-8 -*-
"""Tugas Praktikum Preprocessing

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/156ckHPowU7GF7y7f0XgJtQR0ze4MgnEX
"""

import pandas as pd
#Memuat Data
#Import library yang diperlukan, seperti Pandas dan o	Muat dataset dari file CSV ke dalam DataFrame
df=pd.read_csv('movie_sample_dataset.csv')
df.head()

import numpy as np

#Data yang hilang
print("Jumlah data yang hilang :\n",df.isnull().sum())
#Tipe Data
print("\nType Data : ")
df.dtypes

#Hapus baris yang memiliki nilai NaN di kolom penting seperti gross dan budget
df.dropna(subset=["gross"], axis=0, inplace=True)
df.dropna(subset=["budget"], axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)

# prompt: Atasi nilai yang tidak konsisten atau kesalahan penulisan di kolom, seperti perbedaan antara "Color" dan "color" menjadi "Color"

# Mengubah nilai di kolom 'color' menjadi 'Color' jika ada nilai 'color'
df['color'] = df['color'].str.replace('color', 'Color')
df.head()

import numpy as np
# Hapus baris yang memiliki nilai NaN di kolom 'country'
df.dropna(subset=['country'], axis=0, inplace=True)
df.reset_index(drop=True, inplace=True)

# Mengganti nilai negatif atau N/A pada 'budget' dan 'gross' dengan rata-rata
cols_to_replace = ['budget', 'gross']
for col in cols_to_replace:
    avg_value = df[col].astype(float).mean()
    df[col].replace(np.nan, avg_value, inplace=True)
    print(f"Rata-rata {col}: {avg_value}")

#	Ubah tipe data kolom menjadi tipe data yang sesuai (misalnya, konversi budget dan gross menjadi numerik).
df['budget'] = df['budget'].astype(float)
df['gross'] = df['gross'].astype(float)
df.dtypes

# o	Normalisasi teks untuk memastikan konsistensi (misalnya, mengubah teks menjadi huruf kecil).

df['language'] = df['language'].str.lower()
df.head()

df.to_csv('preprocessing 1.csv', index=False)

